### ISSUE TITLE
I'd like to try lxdocker but the readme.md is pretty minimal in information

### ISSUE THREAD

**Issue by bmullan** [M1cha/lxdocker#1]
I'd like to try lxdocker but the readme.md is pretty minimal in information

I've got the two binaries
**mgserver  lxdocker**  but not sure what next steps in using them looks like?

For instance I thought I'd try lxdocker to create an LXD image using the
Docker Hub app:  ***_[https://hub.docker.com/r/idiotoflinux/defguard-core](https://hub.docker.com/r/idiotoflinux/defguard-core)_***

So I ran lxdocker just to see the syntax for doing the above and all I saw was the following:

> 
_> $ ./lxdocker
> Error: required flag(s) "cache", "lxdimages", "specs" not set
> Usage:
>   lxdocker [flags]
> 
> Flags:
>       --cache string         path to OCI cache
>       -h, --help                 help for lxdocker
>       --imageformat string   format of the generated rootfs' (default "squashfs")
>       --lxdimages string     path to directory for generated LXD images
>       --specs string         path to directory with LXD image specifications_
>   

So I'd like to _suggest maybe adding 1 or 2 examples of the process to use lxdocker that includes using it to 
create an LXD image of 1 or 2 Docker images on Docker Hub?_

I think that would help new users of lxdocker a lot!

**Comment by M1cha** [comment]
You're right. The reason for that is that it was undergoing a massive rewrite with tons of new features. Then, I realized, that I'm basically recreating podman - especially since they added systemd-containers. So I deemed this project useless and will archive this repository now.
